### ISSUE TITLE
Library for the faster ADC081Sxxx ADC chips 

### ISSUE THREAD

**Issue by avandalen** [RobTillaart/ADC081S#1]
Dear Rob, 

Do you think the library also works for the ADC081S chips? These chips also work with SPI but are faster and have also SOT23-6 packages.

Best regards,
Albert

https://avdweb.nl/arduino

Note: Albert refers to MCP_ADC library originally , issue was moved.

**Comment by RobTillaart** [comment]
Thanks for the issue,
Have to dive into the datasheet to verify.  The device might be part of a family so the question needs possibly a broader answer.
Will look into it later this week.

**Comment by RobTillaart** [comment]
Found these datasheets
- https://www.ti.com/lit/ds/symlink/adc081c021.pdf  <<< has far more information.
- https://www.ti.com/lit/ds/symlink/adc081s021.pdf

There are different related chips with resolutions 8,10, 12 bit, extra address pins and/or alert function.

A quick compare shows that the ADC081S series has registers to set where the mcp_adc has not.

So they are not compatible

**Comment by RobTillaart** [comment]
@avandalen 
As far as I know there is no Arduino library for this ADC081S device 
(I made a note on my backlog, between ~50 other missing ones).

**Comment by RobTillaart** [comment]
mmm, a 2nd look, ==> the C-021 == I2C  and S-021 == SPI.

Still not compatible :(  but the SPI version seems pretty straightforward.

**Comment by RobTillaart** [comment]
@avandalen 
I have a few hours and will make a initial version of a library (already doing some dry tests as I have no hardware)

**Comment by RobTillaart** [comment]
@avandalen 
Develop branch created and a PR. 
First dry tests uses 8.9 us per read at 16 MHz SPI so roughly 100 ksps on an ESP32 seems upper limit..
The UNO does stick at around 20 us per read at 8 MHz so about 50 ksps.

There are still things to do, there is a shutdown mode and a normal mode the code now assumes the latter is default.
Furthermore testing with actual hardware is needed to see it works. 
And probably even more, that said the initial version is nearly done or at least within sight.

Do you have hardware to test?

**Comment by RobTillaart** [comment]
@avandalen 

Version 0.1.0 released, if there are problems please open an issue.

**Comment by RobTillaart** [comment]
@avandalen 
Version 0.1.1 released - support for lowPower/shutdown and wakeup.
Version 0.1.2 in develop/PR - support for 10 and 12 bit single channel devices.
no hardware test done, but protocol is fairly straightforward.
multichannel devices need a separate class, as protocol is different and to keep this one optimized

**Comment by RobTillaart** [comment]
@avandalen 
Version 0.1.2 released yesterday.

Further I prototyped 0.1.0 of - https://github.com/RobTillaart/ADC08XS - for the multichannel versions.
Initial release maybe later today.

When time permits (later this week) I will investigate a sort of continuous mode.
See if it is possible to squeeze some more speed from the device.

**Comment by RobTillaart** [comment]
@avandalen 
released 0.1.0 of - https://github.com/RobTillaart/ADC08XS
added an issue to implement a delta read to compare 2 channels.
